### ISSUE TITLE
getting error 0xc0000142

### ISSUE THREAD

**Issue by samimoftheworld** [x15bmu/eyewriterb#3]
getting error 0xc0000142 when i want to use the app with ps3 camera but laptop camera working perfectly

**Comment by cmmishra9** [comment]
This issue comes due to the incompability of aapllication with windows 8 or higher...

**Comment by cmmishra9** [comment]
The other problem may be occured due to digital signal verification.....

**Comment by cmmishra9** [comment]
Sorry not signal its certificate

**Comment by 9999Rishabh** [comment]
Can anybody please help me with this problem!!

**Comment by Anpey9** [comment]
Use windows 7
